### ISSUE TITLE
Delegation flow breaks if confirmation popup is closed

### ISSUE THREAD

**Issue by RiccardoM** [forbole/forbole-x#248] opened 2021-09-02 13:49 UTC
Flow: 
1. Try delegating some tokens
2. Once the confirmation popup opens, close it

The delegation popup will be stuck with the loading button, never changing. This forces the user to go through all the procedure again.

![screenshot-x forbole com-2021 09 02-15_49_29](https://user-images.githubusercontent.com/9119016/131855522-9e55b967-194f-45a4-8c1b-8c3b6fef0969.png)

**Comment by kwunyeung** [comment] 2021-09-07 03:13
Duplicate of #210. Closing now.

**Closed by kwunyeung** 2021-09-07 03:13 UTC
Labels: kind/bug, kind/duplicate, section/staking
