### ISSUE TITLE
Cannot added wallet from extension directly

### ISSUE THREAD

**Issue by kwunyeung** [forbole/forbole-x#215] opened 2021-08-22 17:24 UTC
Wallet from Ledger can't be added from the extension directly as the USB device can't be used from the extension.

Can we have a page running directly with `chrome-extension://`? Or redirect the user to the webapp first?

**Comment by kanniec826** [comment] 2021-08-24 02:54
@calvinkei Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/215?planning-poker)

**Comment by calvinkei** [comment] 2021-08-25 08:53
@kwunyeung i cannot reproduce this. adding ledger wallet works on the extension for me. which browser are you using?

**Comment by kwunyeung** [comment] 2021-08-25 09:35
@calvinkei oh yeah! Just tested and it worked but it's not showing as added via usb device.

**Comment by calvinkei** [comment] 2021-08-25 09:41
@kwunyeung yes i found a minor bug. the ledger icon will show after refreshing. this will be fixed in the next release

**Comment by kwunyeung** [comment] 2021-08-25 09:59
Awesome!

**Closed** 2021-08-30 04:13 UTC
Labels: kind/enhancement, section/wallets, size/L
